# Generated by Django 3.2.12 on 2022-03-16 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marriage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='about',
            field=models.TextField(blank=True, default=None, max_length=300, null=True),
        ),
    ]
