# Generated by Django 3.2.12 on 2022-03-17 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marriage', '0003_alter_customer_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='image',
            field=models.ImageField(blank=True, default='default_profile.png', upload_to='media'),
        ),
    ]
