# Generated by Django 3.2.12 on 2022-03-17 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marriage', '0004_alter_customer_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='image',
            field=models.ImageField(default='default_profile.png', upload_to='media'),
        ),
    ]
