# Generated by Django 3.2.12 on 2022-03-17 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marriage', '0005_alter_customer_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='income',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='image',
            field=models.ImageField(default='default_profile.png', upload_to='profileImg'),
        ),
    ]
