# Generated by Django 3.2.12 on 2022-03-17 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marriage', '0006_auto_20220317_1800'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='height',
            new_name='height_feet',
        ),
        migrations.AddField(
            model_name='customer',
            name='height_inch',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='image',
            field=models.ImageField(blank=True, default='default_profile.png', upload_to='profileImg'),
        ),
    ]
