# Generated by Django 3.2.12 on 2022-03-21 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marriage', '0007_auto_20220317_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intrest',
            name='interested',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intrested_in', to='marriage.customer'),
        ),
        migrations.AlterField(
            model_name='intrest',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_user', to='marriage.customer'),
        ),
    ]
