# Generated by Django 3.2.12 on 2022-03-22 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marriage', '0008_auto_20220321_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='image',
            field=models.ImageField(blank=True, default='default_profile.png', upload_to='profileImg/'),
        ),
    ]
