# Generated by Django 3.2.12 on 2022-03-22 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marriage', '0009_alter_customer_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rejected',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notinterested', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='not_intrested_in', to='marriage.customer')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='this_user', to='marriage.customer')),
            ],
        ),
    ]
