# Generated by Django 3.2.12 on 2022-03-22 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marriage', '0010_rejected'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rejected',
            new_name='Reject',
        ),
    ]
