# Generated by Django 3.2.12 on 2022-03-26 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marriage', '0011_rename_rejected_reject'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matched',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matched_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secound_user_matched', to='marriage.customer')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_user_mathed', to='marriage.customer')),
            ],
        ),
    ]
